@startuml 

component core{
    package studdyBuddy.core;
    package studdyBuddy.json;
}

studdyBuddy.core ..> studdyBuddy.json

component jackson {
}

studdyBuddy.json ..> jackson

component ui {
    package studdyBuddy.ui
}

studdyBuddy.ui ..> studdyBuddy.ui
studdyBuddy.ui ..> studdyBuddy.core
studdyBuddy.ui ..> studdyBuddy.json

@enduml

